=== gseteamproject/gseproject/smartmason/bin/test/common/xml/listTests.dtd
<?xml version='1.0' encoding='us-ascii'?>
	<!--
		DTD for a simple listTester
	-->
	<!ELEMENT TestsList (Test)*>
	<!ELEMENT Test (TestClassName, WhatTest, HowWorkTest, WhenTestPass)>
	<!ATTLIST Test 
	    name     CDATA    #REQUIRED
	    skip     CDATA    #REQUIRED
	>
	<!ELEMENT TestClassName (#PCDATA)>
	<!ELEMENT WhatTest (%inline;)*>
	<!ELEMENT HowWorkTest (%inline;)*>
	<!ELEMENT WhenTestPass (%inline;)*>
	<!ELEMENT em (%inline;)*>
	<!ELEMENT br (%inline;)*>
	<!ELEMENT b (%inline;)*>
	<!ELEMENT LI (%inline;)*>
	<!ELEMENT UL (%inline;)*>

=== gseteamproject/gseproject/smartmason/src/test/pallete/palleteTestsList.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Relative reference to the DTD file does not work when the test suite is in a jar file
<!DOCTYPE TestsList SYSTEM "../common/xml/listTests.dtd" [
	<!ENTITY % inline "#PCDATA|em|br|UL|LI|b">
	]>
-->
	<TestsList> 
		<Test name="Pallete is almost empty" skip="false">
			<TestClassName>test.pallete.tests.PalleteAlmostEmptyTest</TestClassName>
			<WhatTest>"Tests whether a Pallete replies with the right message if it is almost empty (1-4 Blocks)"</WhatTest>
			<HowWorkTest></HowWorkTest>
			<WhenTestPass>"Passes if Pallete replies with 'almost_empty'"</WhenTestPass>
		</Test>
		<Test name="Pallete is empty" skip="false">
			<TestClassName>test.pallete.tests.PalleteEmptyTest</TestClassName>
			<WhatTest>"Tests whether a Pallete replies with the right message if it is empty (0 Blocks)"</WhatTest>
			<HowWorkTest></HowWorkTest>
			<WhenTestPass>"Passes if Pallete replies with 'empty'"</WhenTestPass>
		</Test>
		<Test name="Pallete is not empty anymore" skip="false">
			<TestClassName>test.pallete.tests.PalleteNotEmptyAnymoreTest</TestClassName>
			<WhatTest>"Tests whether a Pallete replies with the right message if it is not empty anymore(5 Blocks)"</WhatTest>
			<HowWorkTest></HowWorkTest>
			<WhenTestPass>"Passes if Pallete replies with 'not_empty_anymore"</WhenTestPass>
		</Test>
	</TestsList>

=== gseteamproject/gseproject/smartmason/bin/test/interPlatform/interPlatformTestsList.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Relative reference to the DTD file does not work when the test suite is in a jar file
<!DOCTYPE TestsList SYSTEM "../common/xml/listTests.dtd" [
	<!ENTITY % inline "#PCDATA|em|br|UL|LI|b">
	]>
-->
	<TestsList> 
		<Test name="Basic inter platform communication" skip="false">
			<TestClassName>test.interPlatform.tests.TestRemotePing</TestClassName>
			<WhatTest> Test the correct handling of the :reply-to slot of an ACL message.</WhatTest>
			<HowWorkTest>An agent is created on a remote platform and then a ping message is sent to it</HowWorkTest>
			<WhenTestPass> The test passes if the agent on the remote platform receives the ping message and replies correctly and no exception is fired.</WhenTestPass>
		</Test>
		
		<Test name="Reply-to" skip="false">
			<TestClassName>test.interPlatform.tests.TestReplyTo</TestClassName>
			<WhatTest> Tests sending and receiving a message to/from an agent on a remote platform.</WhatTest>
			<HowWorkTest>The Tester agent sends a message to agent A specifying B in the reply-to slot. Agent A creates a reply and puts the sender of the incoming message in the reply-to slot of the reply. B does the same so that the Tester should get back a reply from B</HowWorkTest>
			<WhenTestPass> The test passes if the tester gets back a reply from B</WhenTestPass>
		</Test>
		
		<Test name="Message Envelope transfer" skip="false">
			<TestClassName>test.interPlatform.tests.TestEnvelope</TestClassName>
			<WhatTest> Test the correct transfer of the Message Envelope in communication across different platforms.</WhatTest>
			<HowWorkTest> A message is exchanged between two agents living on different platforms with an Envelope including two properties: a Serializable object and a String.</HowWorkTest>
			<WhenTestPass> The test passes if the received Envelope includes the properties as they were set.</WhenTestPass>
		</Test>		
		
		<Test name="Incoming message routing" skip="false">
			<TestClassName>test.interPlatform.tests.TestIncomingMessageRouting</TestClassName>
			<WhatTest> Test the "incoming message routing" mechanism i.e. the case where a message is delivered to an agent on a remote platform and living on a container different from that where the MTP that receives the message is installed.</WhatTest>
			<HowWorkTest> A ping message is exchanged between two agents living on different platforms with an Envelope including two properties: a Serializable object and a String.</HowWorkTest>
			<WhenTestPass> The test passes if the agent on the remote platform receives the ping message and replies correctly and no exception is fired.</WhenTestPass>
		</Test>		
    <Test name="Payload ASCII encoding" skip="false">
			<TestClassName>test.interPlatform.tests.TestCharset</TestClassName>
      <WhatTest>Test the sending of accentuated characters using the default ASCII charset</WhatTest>
			<HowWorkTest> The sender sends a message which content contains accentuated characters</HowWorkTest>
			<WhenTestPass> The test is expected to fail: the agent on the remote platform receives the message without the accentuated characters.</WhenTestPass>
		</Test>		
    <Test name="Payload UTF-8 encoding" skip="false">
			<TestClassName>test.interPlatform.tests.TestCharset</TestClassName>
      <Argument key="pass" value="true">This test is meant to succeed</Argument>
      <Argument key="charset" value="UTF-8">This test is meant to fail</Argument>
      <WhatTest>Test the sending of accentuated characters using the UTF-8 charset. There are two parameters: "pass" to tell if the test shall pass or failed and "charset" to set the charset encoding to be tested.</WhatTest>
			<HowWorkTest> The sender sends a message which content contains accentuated characters</HowWorkTest>
			<WhenTestPass> The agent on the remote platform receives the message with the accentuated characters.</WhenTestPass>
		</Test>		
	</TestsList>
